// Error Handling/error-handling-react/src/App.js
import logo from './logo.svg';
import './App.css';
import React, { useState } from 'react';

function App() {
  // React state to store any error message
  const [error, setError] = useState(null);

  // This function simulates an error and demonstrates error handling using try/catch
  const handleClick = () => {
    try {
      // Simulate an error being thrown (this could represent a failed API call or logic error)
      throw new Error('Something went wrong while processing your request.');
    } catch (err) {
      // Catch the error and update the state with the error message
      setError((err).message);
    }
  };

  return (
    <div>
      {/* Button triggers the error when clicked */}
      <button onClick={handleClick}>Trigger Error</button>

      {/* If there is an error, it will be displayed in red text */}
      {error && <p style={{ color: 'red' }}>{error}</p>}
    </div>
  );
}

export default App;

// Error Handling/error-handling-vue/src/App.vue

//---------------------------------------- VUE ERROR HANDLING ------------------------------------
<template>
  <div>
    <!-- Button triggers the error when clicked -->
    <button @click="handleClick">Trigger Error</button>

    <!-- If there's an error, it will be displayed in red -->
    <p v-if="error" style="color: red">{{ error }}</p>
  </div>
</template>

<script setup>
// Import Vue's reactivity system
import { ref } from 'vue';

// Declare a reactive variable to hold any error message
const error = ref(null);

// Function to simulate and handle an error
function handleClick() {
  try {
    // Simulate an error being thrown
    throw new Error('Something went wrong while processing your request.');
  } catch (err) {
    // Assign the error message to the reactive `error` variable
    error.value = err.message;
  }
}
</script>
